services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/docker/bingogen/ingest:/var/ingest
    environment:
      DB_CREDENTIALS: 'jdbc:postgresql://db:5432/bingogen,org.postgresql.Driver,postgres,postgres'
      ASSET_INGEST: '/var/ingest'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_DB: bingogen
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      retries: 10
      start_period: 5s
      timeout: 10s
